package windowsformsapp1.properties;

import windowsformsapp1.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Runtime.CompilerServices.CompilerGeneratedAttribute()][System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")] internal sealed partial class Settings: System.Configuration.ApplicationSettingsBase
public final class Settings extends System.Configuration.ApplicationSettingsBase
{

	private static Settings defaultInstance = ((Settings)(System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

	public static Settings getDefault()
	{
		return defaultInstance;
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Configuration.ApplicationScopedSettingAttribute()][System.Diagnostics.DebuggerNonUserCodeAttribute()][System.Configuration.SpecialSettingAttribute(System.Configuration.SpecialSetting.ConnectionString)][System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-52O598N\\MSSQLSERVERCPY;Initial Catalog=gdmu;User ID=sa;Passwo" + "rd=123")] public string gdmuConnectionString
	public String getGdmuConnectionString()
	{
		return ((String)(this.get("gdmuConnectionString")));
	}
}